source "https://rubygems.org"

ruby "3.3.0"

gem "rails", "~> 7.1"
gem "pg", "~> 1.5"
gem "puma", "~> 6.0"
gem "rack-cors"
gem "faraday"
gem "faraday-retry"
gem "dotenv-rails"
gem "jbuilder"
gem "bootsnap", require: false
gem "matrix"          # required by prawn on Ruby 3.1+
gem "prawn"
gem "prawn-table"

# Background jobs
gem "sidekiq", "~> 7.0"          # job queue backed by Redis
gem "sidekiq-cron", "~> 1.12"    # cron-style recurring job scheduler

group :development, :test do
  gem "debug"
  gem "rspec-rails"
end
